### ISSUE TITLE
Add metadata to the .md files

### ISSUE THREAD

**Issue by jtomasek** [e-minguez/k3s-versions#18]
It would be nice to add '[frontmatter](https://www.gatsbyjs.com/docs/tutorial/getting-started/part-5/#frontmatter)' metadata (e.g. version and date) to the version details .md files if possible. (See the link to Gatsby docs).

**Comment by e-minguez** [comment]
Sure! Any proposal on what it should look like?

I agree version and publish date should be a must but we can add more stuff if needed.
